/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Estudiante
 */
public class frmCrud extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmList
     */
    public frmCrud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCli = new javax.swing.JTable();
        btnEliminarCli = new javax.swing.JButton();
        btnBuscarCli = new javax.swing.JButton();
        btnInsertarCli = new javax.swing.JButton();
        btnActualizarCli = new javax.swing.JButton();
        btnPdfCli = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMerc = new javax.swing.JTable();
        btnInsertarMerc = new javax.swing.JButton();
        btnBuscarMerc = new javax.swing.JButton();
        btnActualizarMerc = new javax.swing.JButton();
        btnEliminarMerc = new javax.swing.JButton();
        btnPdfMerc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnvios = new javax.swing.JTable();
        btnInsertarEnv = new javax.swing.JButton();
        btnBuscarEnv = new javax.swing.JButton();
        btnActualizarEnv = new javax.swing.JButton();
        btnEliminarEnv = new javax.swing.JButton();
        btnPdfEnv = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblCli);

        btnEliminarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.jpg"))); // NOI18N
        btnEliminarCli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBuscarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar.jpg"))); // NOI18N
        btnBuscarCli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnInsertarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insertar.jpg"))); // NOI18N
        btnInsertarCli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnActualizarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/actualizar.jpg"))); // NOI18N
        btnActualizarCli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPdfCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pdf.jpg"))); // NOI18N
        btnPdfCli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEliminarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsertarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarCli, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnPdfCli))
                .addGap(228, 228, 228))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnInsertarCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizarCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPdfCli)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Lista Clientes", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        tblMerc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Kilos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblMerc);

        btnInsertarMerc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insertar.jpg"))); // NOI18N
        btnInsertarMerc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBuscarMerc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar.jpg"))); // NOI18N
        btnBuscarMerc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnActualizarMerc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/actualizar.jpg"))); // NOI18N
        btnActualizarMerc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEliminarMerc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.jpg"))); // NOI18N
        btnEliminarMerc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPdfMerc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pdf.jpg"))); // NOI18N
        btnPdfMerc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInsertarMerc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarMerc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarMerc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarMerc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPdfMerc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(239, 239, 239))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnInsertarMerc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarMerc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarMerc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarMerc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPdfMerc)
                .addGap(29, 29, 29))
        );

        jTabbedPane2.addTab("Lista Mercancia ", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tblEnvios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Envio", "Identificacion", "Nombre", "Codigo Merc", "Descrip Merc", "Kilos", "Origen", "Destino", "Valor Envio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnvios);

        btnInsertarEnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insertar.jpg"))); // NOI18N
        btnInsertarEnv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBuscarEnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar.jpg"))); // NOI18N
        btnBuscarEnv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnActualizarEnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/actualizar.jpg"))); // NOI18N
        btnActualizarEnv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEliminarEnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.jpg"))); // NOI18N
        btnEliminarEnv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPdfEnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pdf.jpg"))); // NOI18N
        btnPdfEnv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Total Envio: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarEnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarEnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertarEnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarEnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPdfEnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnInsertarEnv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarEnv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarEnv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarEnv)
                        .addGap(98, 98, 98)
                        .addComponent(btnPdfEnv)
                        .addGap(15, 15, 15))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lista Envios", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getBtnActualizarCli() {
        return btnActualizarCli;
    }

    public void setBtnActualizarCli(JButton btnActualizarCli) {
        this.btnActualizarCli = btnActualizarCli;
    }

    public JButton getBtnBuscarCli() {
        return btnBuscarCli;
    }

    public void setBtnBuscarCli(JButton btnBuscarCli) {
        this.btnBuscarCli = btnBuscarCli;
    }

    public JButton getBtnEliminarCli() {
        return btnEliminarCli;
    }

    public void setBtnEliminarCli(JButton btnEliminarCli) {
        this.btnEliminarCli = btnEliminarCli;
    }

    public JButton getBtnInsertarCli() {
        return btnInsertarCli;
    }

    public void setBtnInsertarCli(JButton btnInsertarCli) {
        this.btnInsertarCli = btnInsertarCli;
    }

    public JButton getBtnPdfCli() {
        return btnPdfCli;
    }

    public void setBtnPdfCli(JButton btnPdfCli) {
        this.btnPdfCli = btnPdfCli;
    }

    public JTable getTblCli() {
        return tblCli;
    }

    public void setTblCli(JTable tblCli) {
        this.tblCli = tblCli;
    }

    public JButton getBtnActualizarMerc() {
        return btnActualizarMerc;
    }

    public void setBtnActualizarMerc(JButton btnActualizarMerc) {
        this.btnActualizarMerc = btnActualizarMerc;
    }


    public JButton getBtnBuscarMerc() {
        return btnBuscarMerc;
    }

    public void setBtnBuscarMerc(JButton btnBuscarMerc) {
        this.btnBuscarMerc = btnBuscarMerc;
    }

    public JButton getBtnEliminarMerc() {
        return btnEliminarMerc;
    }

    public void setBtnEliminarMerc(JButton btnEliminarMerc) {
        this.btnEliminarMerc = btnEliminarMerc;
    }

    public JButton getBtnInsertarMerc() {
        return btnInsertarMerc;
    }

    public void setBtnInsertarMerc(JButton btnInsertarMerc) {
        this.btnInsertarMerc = btnInsertarMerc;
    }

    public JButton getBtnPdfMerc() {
        return btnPdfMerc;
    }

    public void setBtnPdfMerc(JButton btnPdfMerc) {
        this.btnPdfMerc = btnPdfMerc;
    }

    public JTable getTblEnvios() {
        return tblEnvios;
    }

    public void setTblEnvios(JTable tblEnvios) {
        this.tblEnvios = tblEnvios;
    }

    public JTable getTblMerc() {
        return tblMerc;
    }

    public void setTblMerc(JTable tblMerc) {
        this.tblMerc = tblMerc;
    }

    public JButton getBtnActualizarEnv() {
        return btnActualizarEnv;
    }

    public void setBtnActualizarEnv(JButton btnActualizarEnv) {
        this.btnActualizarEnv = btnActualizarEnv;
    }

    public JButton getBtnBuscarEnv() {
        return btnBuscarEnv;
    }

    public void setBtnBuscarEnv(JButton btnBuscarEnv) {
        this.btnBuscarEnv = btnBuscarEnv;
    }

    public JButton getBtnEliminarEnv() {
        return btnEliminarEnv;
    }

    public void setBtnEliminarEnv(JButton btnEliminarEnv) {
        this.btnEliminarEnv = btnEliminarEnv;
    }

    public JButton getBtnInsertarEnv() {
        return btnInsertarEnv;
    }

    public void setBtnInsertarEnv(JButton btnInsertarEnv) {
        this.btnInsertarEnv = btnInsertarEnv;
    }

    public JButton getBtnPdfEnv() {
        return btnPdfEnv;
    }

    public void setBtnPdfEnv(JButton btnPdfEnv) {
        this.btnPdfEnv = btnPdfEnv;
    }

    public JLabel getLblTotal() {
        return lblTotal;
    }

    public void setLblTotal(JLabel lblTotal) {
        this.lblTotal = lblTotal;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCli;
    private javax.swing.JButton btnActualizarEnv;
    private javax.swing.JButton btnActualizarMerc;
    private javax.swing.JButton btnBuscarCli;
    private javax.swing.JButton btnBuscarEnv;
    private javax.swing.JButton btnBuscarMerc;
    private javax.swing.JButton btnEliminarCli;
    private javax.swing.JButton btnEliminarEnv;
    private javax.swing.JButton btnEliminarMerc;
    private javax.swing.JButton btnInsertarCli;
    private javax.swing.JButton btnInsertarEnv;
    private javax.swing.JButton btnInsertarMerc;
    private javax.swing.JButton btnPdfCli;
    private javax.swing.JButton btnPdfEnv;
    private javax.swing.JButton btnPdfMerc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCli;
    private javax.swing.JTable tblEnvios;
    private javax.swing.JTable tblMerc;
    // End of variables declaration//GEN-END:variables
}
