/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author crist
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrin
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnEscritorio = new javax.swing.JDesktopPane();
        lblFechayHora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuRegCliente = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuRegMercancia = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuRegEnvio = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        mnuCRUD = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        mnuAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFechayHora.setBackground(new java.awt.Color(0, 0, 0));
        lblFechayHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFechayHora.setText("00:00:00");
        jpnEscritorio.add(lblFechayHora);
        lblFechayHora.setBounds(500, 520, 180, 22);
        jpnEscritorio.add(jScrollPane1);
        jScrollPane1.setBounds(0, 450, 2, 2);

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/marchivo.jpg"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");
        fileMenu.add(jSeparator1);

        mnuRegCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuRegCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mcliente.jpg"))); // NOI18N
        mnuRegCliente.setText("Registrar Cliente");
        fileMenu.add(mnuRegCliente);
        fileMenu.add(jSeparator2);

        mnuRegMercancia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mnuRegMercancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mmercancia.jpg"))); // NOI18N
        mnuRegMercancia.setText("Registrar Mercancia");
        fileMenu.add(mnuRegMercancia);
        fileMenu.add(jSeparator3);

        mnuRegEnvio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mnuRegEnvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menvios.jpg"))); // NOI18N
        mnuRegEnvio.setText("Registrar Envio");
        fileMenu.add(mnuRegEnvio);
        fileMenu.add(jSeparator4);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/msalir.jpg"))); // NOI18N
        mnuSalir.setText("Salir");
        fileMenu.add(mnuSalir);

        menuBar.add(fileMenu);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mconsultar.jpg"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Consultar");

        mnuCRUD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        mnuCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mcrud.jpg"))); // NOI18N
        mnuCRUD.setText("CRUD");
        editMenu.add(mnuCRUD);

        menuBar.add(editMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mayuda.jpg"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        mnuAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/macerca.jpg"))); // NOI18N
        mnuAcerca.setMnemonic('c');
        mnuAcerca.setText("Acerca de");
        mnuAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaActionPerformed(evt);
            }
        });
        helpMenu.add(mnuAcerca);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAcercaActionPerformed

    public JDesktopPane getJpnEscritorio() {
        return jpnEscritorio;
    }

    public void setJpnEscritorio(JDesktopPane jpnEscritorio) {
        this.jpnEscritorio = jpnEscritorio;
    }

    public JMenuItem getMnuRegCliente() {
        return mnuRegCliente;
    }

    public void setMnuRegCliente(JMenuItem mnuRegCliente) {
        this.mnuRegCliente = mnuRegCliente;
    }

    public JMenuItem getMnuRegEnvio() {
        return mnuRegEnvio;
    }

    public void setMnuRegEnvio(JMenuItem mnuRegEnvio) {
        this.mnuRegEnvio = mnuRegEnvio;
    }

    public JMenuItem getMnuRegMercancia() {
        return mnuRegMercancia;
    }

    public void setMnuRegMercancia(JMenuItem mnuRegMercancia) {
        this.mnuRegMercancia = mnuRegMercancia;
    }

    public JMenuItem getMnuSalir() {
        return mnuSalir;
    }

    public void setMnuSalir(JMenuItem mnuSalir) {
        this.mnuSalir = mnuSalir;
    }

    public JMenuItem getMnuLCli() {
        return mnuCRUD;
    }

    public void setMnuLCli(JMenuItem mnuLCli) {
        this.mnuCRUD = mnuLCli;
    }

    public JMenuItem getMnuAcerca() {
        return mnuAcerca;
    }

    public void setMnuAcerca(JMenuItem mnuAcerca) {
        this.mnuAcerca = mnuAcerca;
    }

    public JLabel getLblFechayHora() {
        return lblFechayHora;
    }

    public void setLblFechayHora(JLabel lblFechayHora) {
        this.lblFechayHora = lblFechayHora;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JDesktopPane jpnEscritorio;
    private javax.swing.JLabel lblFechayHora;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAcerca;
    private javax.swing.JMenuItem mnuCRUD;
    private javax.swing.JMenuItem mnuRegCliente;
    private javax.swing.JMenuItem mnuRegEnvio;
    private javax.swing.JMenuItem mnuRegMercancia;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenuItem getMnuCRUD() {
        return mnuCRUD;
    }

    public void setMnuCRUD(javax.swing.JMenuItem mnuCRUD) {
        this.mnuCRUD = mnuCRUD;
    }

}
