/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author crist
 */
public class frmRegEnvio extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegEnv
     */
    public frmRegEnvio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPar1 = new javax.swing.JLabel();
        lblNro = new javax.swing.JLabel();
        lblTitu = new javax.swing.JLabel();
        jpn3 = new javax.swing.JPanel();
        cmbEnvio = new javax.swing.JComboBox<>();
        lblPar2 = new javax.swing.JLabel();
        lblPar3 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        lblPar4 = new javax.swing.JLabel();
        jpn1 = new javax.swing.JPanel();
        lblPar6 = new javax.swing.JLabel();
        txtIdCli = new javax.swing.JTextField();
        lblPar5 = new javax.swing.JLabel();
        jpn2 = new javax.swing.JPanel();
        lblPar8 = new javax.swing.JLabel();
        txtCodMer = new javax.swing.JTextField();
        lblPar7 = new javax.swing.JLabel();
        lblPar9 = new javax.swing.JLabel();
        txtKilos = new javax.swing.JTextField();
        btnVKilos = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();
        btnBMerc = new javax.swing.JButton();
        btnBCli = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));

        lblPar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPar1.setText("Nro.");

        lblNro.setBackground(new java.awt.Color(0, 0, 0));
        lblNro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitu.setText("REGISTRO ENVIO");

        jpn3.setBackground(new java.awt.Color(153, 153, 153));
        jpn3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbEnvio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aereo", "Terrestre" }));
        cmbEnvio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEnvioItemStateChanged(evt);
            }
        });
        cmbEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnvioActionPerformed(evt);
            }
        });

        lblPar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPar2.setText("Tipo de Envío: ");

        lblPar3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPar3.setText("Origen:");

        txtOrigen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigenActionPerformed(evt);
            }
        });

        txtDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoActionPerformed(evt);
            }
        });

        lblPar4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPar4.setText("Destino:");

        javax.swing.GroupLayout jpn3Layout = new javax.swing.GroupLayout(jpn3);
        jpn3.setLayout(jpn3Layout);
        jpn3Layout.setHorizontalGroup(
            jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPar2)
                    .addComponent(lblPar3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPar4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbEnvio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOrigen)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jpn3Layout.setVerticalGroup(
            jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPar2)
                    .addComponent(cmbEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPar3)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPar4)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jpn1.setBackground(new java.awt.Color(153, 153, 153));
        jpn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPar6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPar6.setText("Ingrese Identificación:");

        txtIdCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCliActionPerformed(evt);
            }
        });

        lblPar5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPar5.setText("CLIENTE");

        javax.swing.GroupLayout jpn1Layout = new javax.swing.GroupLayout(jpn1);
        jpn1.setLayout(jpn1Layout);
        jpn1Layout.setHorizontalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(lblPar5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn1Layout.createSequentialGroup()
                        .addComponent(lblPar6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdCli)))
                .addGap(24, 24, 24))
        );
        jpn1Layout.setVerticalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPar5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPar6)
                    .addComponent(txtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jpn2.setBackground(new java.awt.Color(153, 153, 153));
        jpn2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPar8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPar8.setText("Iingrese Código:");

        txtCodMer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodMer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodMerActionPerformed(evt);
            }
        });

        lblPar7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPar7.setText("MERCANCIA");

        lblPar9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPar9.setText("ingrese cant Kilos:");

        txtKilos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtKilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilosActionPerformed(evt);
            }
        });

        btnVKilos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVKilos.setText("Validar");

        javax.swing.GroupLayout jpn2Layout = new javax.swing.GroupLayout(jpn2);
        jpn2.setLayout(jpn2Layout);
        jpn2Layout.setHorizontalGroup(
            jpn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn2Layout.createSequentialGroup()
                        .addComponent(lblPar9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKilos, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVKilos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn2Layout.createSequentialGroup()
                        .addComponent(lblPar7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpn2Layout.createSequentialGroup()
                        .addComponent(lblPar8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodMer)))
                .addGap(25, 25, 25))
        );
        jpn2Layout.setVerticalGroup(
            jpn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPar7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPar8)
                    .addComponent(txtCodMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPar9)
                    .addComponent(txtKilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVKilos))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnReg.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnReg.setText("Registrar");
        btnReg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBMerc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBMerc.setText("Buscar Mercancia");
        btnBMerc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBCli.setText("Buscar Cliente");
        btnBCli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPar1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTitu)
                                        .addGap(96, 96, 96))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(btnBCli, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btnBMerc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitu)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBCli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBMerc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEnvioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEnvioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEnvioItemStateChanged

    private void cmbEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEnvioActionPerformed

    private void txtOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigenActionPerformed

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoActionPerformed

    private void txtIdCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCliActionPerformed

    private void txtCodMerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodMerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodMerActionPerformed

    private void txtKilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilosActionPerformed

    public JButton getBtnReg() {
        return btnReg;
    }

    public void setBtnReg(JButton btnReg) {
        this.btnReg = btnReg;
    }

    public JComboBox<String> getCmbEnvio() {
        return cmbEnvio;
    }

    public void setCmbEnvio(JComboBox<String> cmbEnvio) {
        this.cmbEnvio = cmbEnvio;
    }

    public JLabel getLblNro() {
        return lblNro;
    }

    public void setLblNro(JLabel lblNro) {
        this.lblNro = lblNro;
    }

    public JTextField getTxtCodMer() {
        return txtCodMer;
    }

    public void setTxtCodMer(JTextField txtCodMer) {
        this.txtCodMer = txtCodMer;
    }

    public JTextField getTxtDestino() {
        return txtDestino;
    }

    public void setTxtDestino(JTextField txtDestino) {
        this.txtDestino = txtDestino;
    }

    public JTextField getTxtIdCli() {
        return txtIdCli;
    }

    public void setTxtIdCli(JTextField txtIdCli) {
        this.txtIdCli = txtIdCli;
    }

    public JTextField getTxtOrigen() {
        return txtOrigen;
    }

    public void setTxtOrigen(JTextField txtOrigen) {
        this.txtOrigen = txtOrigen;
    }

    public JPanel getJpn1() {
        return jpn1;
    }

    public void setJpn1(JPanel jpn1) {
        this.jpn1 = jpn1;
    }

    public JPanel getJpn2() {
        return jpn2;
    }

    public void setJpn2(JPanel jpn2) {
        this.jpn2 = jpn2;
    }

    public JPanel getJpn3() {
        return jpn3;
    }

    public void setJpn3(JPanel jpn3) {
        this.jpn3 = jpn3;
    }

    public JButton getBtnBCli() {
        return btnBCli;
    }

    public void setBtnBCli(JButton btnBCli) {
        this.btnBCli = btnBCli;
    }

    public JButton getBtnBMerc() {
        return btnBMerc;
    }

    public void setBtnBMerc(JButton btnBMerc) {
        this.btnBMerc = btnBMerc;
    }

    public JButton getBtnVKilos() {
        return btnVKilos;
    }

    public void setBtnVKilos(JButton btnVKilos) {
        this.btnVKilos = btnVKilos;
    }

    public JTextField getTxtKilos() {
        return txtKilos;
    }

    public void setTxtKilos(JTextField txtKilos) {
        this.txtKilos = txtKilos;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBCli;
    private javax.swing.JButton btnBMerc;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnVKilos;
    private javax.swing.JComboBox<String> cmbEnvio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpn1;
    private javax.swing.JPanel jpn2;
    private javax.swing.JPanel jpn3;
    private javax.swing.JLabel lblNro;
    private javax.swing.JLabel lblPar1;
    private javax.swing.JLabel lblPar2;
    private javax.swing.JLabel lblPar3;
    private javax.swing.JLabel lblPar4;
    private javax.swing.JLabel lblPar5;
    private javax.swing.JLabel lblPar6;
    private javax.swing.JLabel lblPar7;
    private javax.swing.JLabel lblPar8;
    private javax.swing.JLabel lblPar9;
    private javax.swing.JLabel lblTitu;
    private javax.swing.JTextField txtCodMer;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtIdCli;
    private javax.swing.JTextField txtKilos;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
